export { validateTenantContext } from './types';
export type {
  AuthType,
  CollectionSnapshot,
  DeleteJobSnapshot,
  DeleteJobState,
  JobDefinition,
  JobEnvelope,
  JobHandler,
  KnowledgeBaseSnapshot,
  KnowledgeItemIndexValue,
  KnowledgeItemSnapshot,
  ObjectRef,
  PageResult,
  PermissionContext,
  PortCallOptions,
  ProcessingJobSnapshot,
  RequestContext,
  TenantContext,
} from './types';

export type {
  CollectionRepository,
  DeleteJobRepository,
  KnowledgeBaseRepository,
  KnowledgeItemRepository,
  ProcessingJobRepository,
} from './repositories';

export type {
  AdminDatasetPort,
  ArchiveStatusPort,
  AuditPort,
  AuditRecord,
  AuthSubject,
  AuthSubjectProvider,
  BackupToolPort,
  CallerPermissionContext,
  CollaboratorPermission,
  DatasetEvent,
  DatasetEventPort,
  DatasetMetricsPort,
  DatasetNotificationPort,
  DatasetPermissionPort,
  DatasetSearchPort,
  DatasetSourceProvider,
  DatasetSyncPort,
  DegradationMode,
  DegradationPolicy,
  FailureQueryPort,
  FailureRecord,
  FeatureFlagProvider,
  FullTextHit,
  FullTextStore,
  HealthProbePort,
  ImageTaskResult,
  ImageTrainingProcessorPort,
  IndexDiff,
  LoggerPort,
  MigrationRegistryPort,
  ModelCapability,
  ModelRegistryPort,
  MongoIndexManagerPort,
  Notification,
  NotificationEvent,
  NotifyPort,
  ObjectStorePort,
  PdfEnhanceProviderPort,
  PdfResult,
  PermissionSnapshotValue,
  ProbeResult,
  ProviderImageQuery,
  ReconcileResultPort,
  SBOMGeneratorPort,
  SourceReadRequest,
  SourceReadResult,
  SyncResult,
  TaskEnvelope,
  TaskResult,
  TenantContextProvider,
  TenantQuotaProvider,
  TrainingProcessorPort,
  TransferDatasetOwnerPort,
  UpdateDatasetCollaboratorsPort,
  VectorController,
  VectorRecord,
  VectorSearchHit,
} from './capabilities';

export { DEFAULT_PORT_IDS, createDefaultPorts, createUnimplementedPort } from './defaults';
export type { ServicePorts } from './defaults';
